#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20
#define ID_TEX_BACKGROUND 30


#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_BACKBRICK 6
#define OBJECT_TYPE_SAND 7
#define OBJECT_TYPE_CLOUNDSMILE 8
#define OBJECT_TYPE_MYSBOX 9
#define OBJECT_TYPE_TROOPA 10
#define OBJECT_TYPE_TOPPIPL 200
#define OBJECT_TYPE_TOPPIPR 201
#define OBJECT_TYPE_BOTPIPL 202
#define OBJECT_TYPE_BOTPIPR 203
#define OBJECT_TYPE_TOPCLOUNDL 210
#define OBJECT_TYPE_TOPCLOUNDM 211
#define OBJECT_TYPE_TOPCLOUNDR 212
#define OBJECT_TYPE_BOTCLOUNDL 213
#define OBJECT_TYPE_BOTCLOUNDM 214
#define OBJECT_TYPE_BOTCLOUNDR 215

#define OBJECT_TYPE_TOPSHAPE0L 310
#define OBJECT_TYPE_TOPSHAPE0M 311
#define OBJECT_TYPE_TOPSHAPE0R 312
#define OBJECT_TYPE_MIDSHAPE0L 313
#define OBJECT_TYPE_MIDSHAPE0M 314
#define OBJECT_TYPE_MIDSHAPE0R 315
#define OBJECT_TYPE_BOTSHAPE0L 316
#define OBJECT_TYPE_BOTSHAPE0M 317
#define OBJECT_TYPE_BOTSHAPE0R 318

#define OBJECT_TYPE_TOPSHAPE1L 320
#define OBJECT_TYPE_TOPSHAPE1M 321
#define OBJECT_TYPE_TOPSHAPE1R 322
#define OBJECT_TYPE_MIDSHAPE1L 323
#define OBJECT_TYPE_MIDSHAPE1M 324
#define OBJECT_TYPE_MIDSHAPE1R 325
#define OBJECT_TYPE_BOTSHAPE1L 326
#define OBJECT_TYPE_BOTSHAPE1M 327
#define OBJECT_TYPE_BOTSHAPE1R 328

#define OBJECT_TYPE_TOPSHAPE2L 330
#define OBJECT_TYPE_TOPSHAPE2M 331
#define OBJECT_TYPE_TOPSHAPE2R 332
#define OBJECT_TYPE_MIDSHAPE2L 333
#define OBJECT_TYPE_MIDSHAPE2M 334
#define OBJECT_TYPE_MIDSHAPE2R 335
#define OBJECT_TYPE_BOTSHAPE2L 336
#define OBJECT_TYPE_BOTSHAPE2M 337
#define OBJECT_TYPE_BOTSHAPE2R 338

#define OBJECT_TYPE_TOPSHAPE3L 340
#define OBJECT_TYPE_TOPSHAPE3M 341
#define OBJECT_TYPE_TOPSHAPE3R 342
#define OBJECT_TYPE_MIDSHAPE3L 343
#define OBJECT_TYPE_MIDSHAPE3M 344
#define OBJECT_TYPE_MIDSHAPE3R 345
#define OBJECT_TYPE_BOTSHAPE3L 346
#define OBJECT_TYPE_BOTSHAPE3M 347
#define OBJECT_TYPE_BOTSHAPE3R 348
#define OBJECT_TYPE_TOPGRASSL 400
#define OBJECT_TYPE_TOPGRASSR 401
#define OBJECT_TYPE_BOTGRASSL 402
#define OBJECT_TYPE_BOTGRASSR 403
#define OBJECT_TYPE_BOTGRASSLa 404
#define OBJECT_TYPE_BOTGRASSRa 405
#define OBJECT_TYPE_MIDGRASS 406


#define OBJECT_TYPE_PORTAL	50


#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#pragma endregion 

#define ID_SPRITE_BRICK 20000
#define ID_SPRITE_BACKBRICK 25000
#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)

#define ID_SPRITE_COIN 40000

#define ID_SPRITE_CLOUD 50000
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+3000)
